### ISSUE TITLE
AWS/S3 (for image upload) not working on play-2.3.0

### ISSUE THREAD

**Issue by mikesname** [mikesname/docview#267]
```
java.lang.NoClassDefFoundError: play/api/libs/ws/SignatureCalculator
    at fly.play.aws.Aws$.withSigner(Aws.scala:41) ~[play-aws-utils_2.10-2.4.2.jar:2.4.2]
    at fly.play.s3.S3.awsWithSigner$lzycompute(S3.scala:54) ~[play-s3_2.10-3.3.3.jar:3.3.3]
    at fly.play.s3.S3.awsWithSigner(S3.scala:54) ~[play-s3_2.10-3.3.3.jar:3.3.3]
    at fly.play.s3.S3.put(S3.scala:94) ~[play-s3_2.10-3.3.3.jar:3.3.3]
    at fly.play.s3.Bucket.add(Bucket.scala:91) ~[play-s3_2.10-3.3.3.jar:3.3.3]
    at controllers.portal.Profile.controllers$portal$Profile$$convertAndUploadFile(Profile.scala:253)
```
